#!/bin/bash

DIR=`dirname $0`

ROOT_DIR=sc-voice/ebt-site
git config remote.origin.url | grep "$ROOT_DIR" > /dev/null ; RC=$?
if [ "$RC" == "0" ]; then
  echo -e "$SCRIPT: npm install --save @sc-voice/scv-static"
  npm install --save @sc-voice/scv-static@latest
  $DIR/git-commit-version
fi

$DIR/pull-upstream

