#!/bin/bash
DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`

echo -e "$SCRIPT: start"

echo -e "$SCRIPT: checking git..."
git checkout package-lock.json
git status 2> /dev/null | grep "nothing to commit"; RC=$?
if [ "$RC" == "0" ]; then
  echo -e "$SCRIPT: git is clean (OK)"
else
  echo -e "$SCRIPT: git is NOT clean (CANCELED)"
  git status
  exit -1
fi

export BABEL_ENV=deploy
$DIR/repo-info > ebt-repo.json
$DIR/wiki-images
npm run version:nuxt
npm run generate 2>&1
git add content
git commit -am "nuxt-routes"

npm run deploy:branch &&\
git push &&\
find dist &&\
RC=$?

echo -e "$SCRIPT: done => $RC"
