#!/bin/bash

DIR=`dirname $0`
SCRIPT=`basename $0 | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
ROOT_DIR=sc-voice/ebt-site

echo -e "$SCRIPT: git pull => `git pull 2>&1`"

git config remote.origin.url | grep "$ROOT_DIR" > /dev/null ; RC=$?
if [ "$RC" == "0" ]; then
  echo -e "$SCRIPT: $ROOT_DIR detected (no action taken)"
  exit 0
fi
echo -e "$SCRIPT: pulling $ROOT_DIR ..."

git config remote.upstream.url https://github.com/sc-voice/ebt-site.git
git config remote.upstream.fetch +refs/heads/*:refs/remotes/upstream/*
echo -e "$SCRIPT: git fetch upstream => `git fetch upstream`"

echo -e "$SCRIPT: git merge =>\
`git merge --no-commit --no-edit -s recursive -Xours upstream/main 2>&1`"

EBT_VER=`$DIR/version`
git status | grep 'still merging' ; RC=$?
if [ "$RC" == "0" ]; then
  MSG="$SCRIPT: ebt-site v$EBT_VER => merged"
  echo -e "$MSG"
  git commit -m "$MSG"
  echo -e "$SCRIPT: git push => `git push 2>&1`"
  if [ "$GITHUB_ACTIONS" == "true" ]; then
    $DIR/deploy
  fi
else
  echo -e "$SCRIPT: ebt-site v$EBT_VER => unchanged"
fi
